CREATE TABLE "leads" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"property" text NOT NULL,
	"location" text NOT NULL,
	"price" integer NOT NULL,
	"area" integer,
	"source" text NOT NULL,
	"status" text NOT NULL,
	"ai_score" integer,
	"reasoning" text,
	"recommended_action" text,
	"routing_bucket" text,
	"sla_hours" integer,
	"assigned_team" text,
	"assigned_owner" text,
	"office_name" text,
	"pipeline_stage" text,
	"next_step" text,
	"follow_up_at" timestamp,
	"last_contact_at" timestamp,
	"strategy_goal" text,
	"outreach_channel" text,
	"outreach_message" text,
	"market" text,
	"country_code" text,
	"preferred_language" text,
	"currency_code" text,
	"plan_id" text,
	"plan_name" text,
	"agent_label" text,
	"intelligence_version" integer,
	"contact" text,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
